# Generated by Django 6.0.6 on 2026-06-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('annual_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
