# Generated by Django 6.0.6 on 2026-06-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='source_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
