# Generated by Django 6.0.6 on 2026-06-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0002_person_source_title_person_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
