# Generated by Django 6.0.6 on 2026-06-09 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0003_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osoby.party')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='osoby.person')),
            ],
        ),
    ]
