# Generated by Django 6.0.6 on 2026-06-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0004_partymembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partymembership',
            options={'ordering': ['start_year']},
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='partymembership',
            constraint=models.UniqueConstraint(fields=('person', 'party', 'start_year', 'end_year'), name='unique_party_membership'),
        ),
    ]
