# Generated by Django 6.0.6 on 2026-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0005_alter_partymembership_options_person_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='voivodeship',
            field=models.CharField(blank=True, choices=[('dolnoslaskie', 'Dolnośląskie'), ('kujawsko_pomorskie', 'Kujawsko-Pomorskie'), ('lubelskie', 'Lubelskie'), ('lubuskie', 'Lubuskie'), ('lodzkie', 'Łódzkie'), ('malopolskie', 'Małopolskie'), ('mazowieckie', 'Mazowieckie'), ('opolskie', 'Opolskie'), ('podkarpackie', 'Podkarpackie'), ('podlaskie', 'Podlaskie'), ('pomorskie', 'Pomorskie'), ('slaskie', 'Śląskie'), ('swietokrzyskie', 'Świętokrzyskie'), ('warminsko_mazurskie', 'Warmińsko-Mazurskie'), ('wielkopolskie', 'Wielkopolskie'), ('zachodniopomorskie', 'Zachodniopomorskie')], max_length=50),
        ),
    ]
