# Generated by Django 6.0.6 on 2026-06-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0006_person_voivodeship'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
