# Generated by Django 6.0.6 on 2026-06-09 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0008_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='osoby.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
