# Generated by Django 6.0.6 on 2026-06-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0010_personvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
