# Generated by Django 6.0.6 on 2026-06-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0011_person_salary_max_person_salary_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='person',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='person',
            name='source_title',
        ),
        migrations.RemoveField(
            model_name='person',
            name='source_url',
        ),
        migrations.AddField(
            model_name='partymembership',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='party',
            field=models.CharField(blank=True, max_length=200, verbose_name='Partia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis działalności'),
        ),
    ]
