# Generated by Django 6.0.6 on 2026-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0012_remove_person_latitude_remove_person_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
