# Generated by Django 6.0.6 on 2026-07-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0014_alter_person_photo_personsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymembership',
            name='family_relation',
            field=models.CharField(blank=True, help_text="Np. 'szwagierka', 'syn', 'żona'. Wypełnij zamiast traktować osobę jako formalnego członka partii - wyświetli się zamiast okresu przynależności.", max_length=255, verbose_name='Powiązanie rodzinne'),
        ),
    ]
